services:
  password:
    image: ghcr.io/backendbyalex/password-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - passworddb
    environment:
      - NODE_ENV=production
      - DB_URI=mongodb://passworddb:27017/passworddb
    volumes:
      - ./.env:/app/.env:ro
      - ./public.pem:/app/public.pem:ro
    restart: unless-stopped
    networks:
      - timelock-network

  passworddb:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - passworddb-data:/data/db
    restart: unless-stopped
    networks:
      - timelock-network

networks:
  timelock-network:
    external: true

volumes:
  passworddb-data:  # Definierar named volume